export const site = {
  name: "Team La Gang",
  fullName: "A.S. Team La Gang",
  track: "RcLandia",
  domain: "teamlagang.it",
  tagline: "Pista RC indoor. Moquette, piloti, divertimento.",
  description:
    "Team La Gang e RcLandia sono una cosa sola: pista RC indoor aperta al pubblico a Scandiano. 1/10 Touring Modificata/Stock/GT-LMH, 1/10 FWD, 1/10 Vaschetta, 1/12 Pancar e GT12/LMH.",
  nav: [
    { label: "Pista", href: "/pista" },
    { label: "Team", href: "/team" },
    { label: "Categorie", href: "/categorie" },
    { label: "Stagione 26/27", href: "/stagione-2026-2027", pulse: true },
    { label: "Eventi", href: "/eventi" },
    { label: "News", href: "/news" },
    { label: "Contatti", href: "/contatti" },
  ],
  categories: [
    {
      slug: "touring-modificata",
      label: "1/10 Touring Modificata",
      short: "Modificata",
      blurb: "Motore e regolatore liberi, nessun vincolo. La classe più spinta del touring elettrico.",
      description:
        "1/10 4WD elettrico senza vincoli di lista: motore brushless libero, regolatore a timing libero, telai full-carbon, sospensioni a triangoli regolabili in ogni direzione. È la categoria tecnicamente più avanzata e veloce, ma il dato grezzo non basta — conta gestire l'energia, montare il setup giusto e restare costanti per tutta la durata della batteria.",
      specs: {
        scale: "1/10",
        drivetrain: "4WD",
        motor: "Libero",
        esc: "Libero",
        ratio: "Libero",
        battery: "Hardcase 2S, max 8,4V",
        body: "Lista EFRA · alettone non oltre il tetto",
        tires: "Team La Gang Carpet",
        weight: "1280 g",
      },
    },
    {
      slug: "touring-stock",
      label: "1/10 Touring Stock 17.5",
      short: "Stock 17.5",
      blurb: "Motore 17.5T da lista, regolatore senza timing. Tra le touring più diffuse.",
      description:
        "1/10 4WD con motore brushless 17.5T da lista EFRA e regolatore senza timing: la potenza è uguale per tutti, le differenze le fanno guida e setup. È una delle categorie più diffuse nei campionati indoor italiani, con griglie numerose. Contano la cura dell'assetto, la gestione delle gomme e la costanza dal primo all'ultimo giro.",
      specs: {
        scale: "1/10",
        drivetrain: "4WD",
        motor: "Brushless 17.5T (lista EFRA)",
        esc: "Libero, modalità no timing",
        ratio: "Libero",
        battery: "Hardcase 2S, max 8,4V",
        body: "Lista EFRA · alettone non oltre il tetto",
        tires: "Team La Gang Carpet",
        weight: "1280 g",
      },
    },
    {
      slug: "touring-gt",
      label: "1/10 GT / LMH",
      short: "GT/LMH",
      blurb: "Touring 4WD con motore controllato 21.5T e carrozzerie GT, Hypercar e LMH.",
      description:
        "Touring 1/10 4WD con motore brushless 21.5T da lista EFRA e regolatore senza timing, con carrozzerie GT, Hypercar e LMH. La potenza contenuta rende la guida più fluida e gestibile rispetto alle classi più spinte; le carrozzerie riprendono granturismo e prototipi Le Mans reali.",
      specs: {
        scale: "1/10",
        drivetrain: "4WD",
        motor: "Brushless 21.5T (lista EFRA)",
        esc: "Libero, modalità no timing",
        ratio: "Libero",
        battery: "Hardcase 2S, max 8,4V",
        body: "GT / Hypercar / LMH",
        tires: "Ride 26073W",
        weight: "1280 g",
      },
    },
    {
      slug: "fwd",
      label: "1/10 FWD",
      short: "FWD",
      blurb: "Touring 1/10 a trazione anteriore. Comportamento molto diverso dal 4WD.",
      description:
        "Touring 1/10 a sola trazione anteriore: comportamento diverso dal 4WD, con più sottosterzo da gestire, ingressi in curva più tardivi e trazione in uscita da dosare col gas. Motore 21.5T da lista EFRA e regolatore Hobbywing Justock senza timing. Costi contenuti ma buona difficoltà tecnica.",
      specs: {
        scale: "1/10",
        drivetrain: "2WD anteriore",
        motor: "21.5T (lista EFRA)",
        esc: "Hobbywing Justock XR10 / XR10 G3 / G3S, no timing",
        ratio: "Libero",
        battery: "Hardcase 2S, max 8,4V",
        body: "Lista ACI",
        tires: "Ride 26073W",
        weight: "1250 g",
      },
    },
    {
      slug: "vaschetta",
      label: "1/10 Vaschetta",
      short: "Vaschetta",
      blurb: "Telaio a vaschetta e cardano. Semplice ed economica, per chi inizia.",
      description:
        "Telaio 1/10 a vaschetta in plastica e trasmissione a cardano, con combo motore-regolatore Hobbywing Justock obbligata e rapporto minimo di 5 (5.1 sì, 4.9 no). Una classe semplice ed economica, pensata per chi vuole iniziare a gareggiare senza spendere troppo: componenti standard e nessuna corsa al setup. Carrozzerie GT ispirate ad auto reali da competizione.",
      specs: {
        scale: "1/10",
        drivetrain: "Telaio a vaschetta, trasmissione a cardano",
        motor: "Hobbywing Justock 3650 G2/G2.1",
        esc: "Hobbywing Justock XR10 G3-G3S, no timing",
        ratio: "Minimo 5",
        battery: "Hardcase 2S, max 8,4V",
        body: "GT che riproducono auto reali da competizione",
        tires: "Da regolamento in pista",
        weight: "1360 g",
      },
    },
    {
      slug: "pancar",
      label: "1/12 Pan car",
      short: "Pancar",
      blurb: "Pan car 1/12 ad assale rigido. La 1/12 più veloce e tecnica.",
      description:
        "La categoria storica del 1/12 elettrico: telaio piatto ad assale rigido posteriore, senza ammortizzatori (lavora solo il flex laterale del telaio), peso molto ridotto (730 g in ordine di marcia) e batteria 1S a 4,2V. Motore 6.5T da lista EFRA e regolatore senza timing. Velocità elevate su moquette e guida molto diretta, apprezzata soprattutto dai piloti più esperti.",
      specs: {
        scale: "1/12",
        drivetrain: "Pancar, assale rigido",
        motor: "Brushless 6.5T (lista EFRA)",
        esc: "Libero, modalità no timing",
        ratio: "Libero",
        battery: "Hardcase 1S, max 4,2V",
        body: "Lista EFRA",
        tires: "Libere · max 20 mm ant. / 40 mm post.",
        weight: "730 g",
      },
    },
    {
      slug: "gt12",
      label: "1/12 GT12 & LMH",
      short: "GT12",
      blurb: "Pan car 1/12 con motore 13.5T e carrozzerie chiuse LMH/GT.",
      description:
        "Variante più accessibile del 1/12: stesso telaio Pancar ad assale rigido, ma motore brushless 13.5T (meno spinto del 6.5T della Pan car) e carrozzerie chiuse in stile LMH e GT12. Velocità un po' più contenute e gomme Contact obbligate. È nata negli ultimi anni come ingresso al mondo 1/12, senza dover affrontare subito le velocità più alte della Pan car.",
      specs: {
        scale: "1/12",
        drivetrain: "Pancar, assale rigido",
        motor: "Brushless 13.5T (lista EFRA)",
        esc: "Libero, modalità no timing",
        ratio: "Libero",
        battery: "Hardcase 1S, max 4,2V",
        body: "LMH 1/12 e GT12",
        tires: "Contact (JGCF/JT2 ant. · JGCR/JG2CR/JT2/JT3 post.)",
        weight: "790 g",
      },
    },
  ],
  season: {
    key: "2026/27",
    title: "Italian Indoor Series 2026/27",
    rounds: 5,
    classes: [
      "Pan car 1/12",
      "GT12 / LMH",
      "Touring Modificata",
      "Touring Stock",
      "FWD",
      "GT / LMH",
      "Vaschetta",
    ],
    calendar: [
      { date: "11 Ottobre 2026", title: "1ª Prova Italian Indoor Series ’26/27", round: 1, iis: true },
      { date: "25 Ottobre 2026", title: "2ª Prova Italian Indoor Series ’26/27", round: 2, iis: true },
      { date: "15 Novembre 2026", title: "3ª Prova Italian Indoor Series ’26/27", round: 3, iis: true },
      { date: "29 Novembre 2026", title: "Trofeo Hudy Series" },
      { date: "20 Dicembre 2026", title: "Trofeo Schumacher" },
      { date: "16/17 Gennaio 2027", title: "Charity Race ’27", charity: true },
      { date: "7 Febbraio 2027", title: "4ª Prova Italian Indoor Series ’26/27", round: 4, iis: true },
      { date: "28 Febbraio 2027", title: "Campionato Italiano Indoor - ACI", label: "Gara titolata" },
      { date: "21 Marzo 2027", title: "5ª Prova Italian Indoor Series ’26/27", round: 5, iis: true },
    ],
    fees: { oneClass: 30, twoClasses: 40, lateSurcharge: 10 },
    paymentEmail: "info@teamlagang.it",
  },
  social: {
    facebook: "https://www.facebook.com/p/RcLandia-100063565060634/",
    pullstart: "https://pullstart.tv/track/rc-landia?isUpcoming=0",
    myrcm: "https://www.myrcm.ch/myrcm/main?dId[O]=5244&pLa=it&hId[1]=org",
  },
} as const;

export type NavItem = (typeof site.nav)[number];
export type Category = (typeof site.categories)[number];
