export const site = {
  name: "Team La Gang",
  fullName: "A.S. Team La Gang",
  track: "RcLandia",
  domain: "teamlagang.it",
  tagline: "Pista RC indoor. Moquette, piloti, divertimento.",
  description:
    "A.S. Team La Gang gestisce RcLandia, pista RC indoor aperta al pubblico. 1/10 Touring GT/Stock/Modificata, 1/10 FWD, 1/12 GT, 1/12 Pancar, TT02.",
  nav: [
    { label: "Pista", href: "/pista" },
    { label: "Team", href: "/team" },
    { label: "Categorie", href: "/categorie" },
    { label: "Eventi", href: "/eventi" },
    { label: "News", href: "/news" },
    { label: "Contatti", href: "/contatti" },
  ],
  categories: [
    {
      slug: "touring-gt",
      label: "1/10 GT",
      short: "GT",
      blurb: "Touring 4WD vestito GT/Supercar. Motore controllato 21.5T.",
      description:
        "Categoria di mezzo del touring 1/10 4WD: motore brushless 21.5T, regolatore senza timing e carrozzerie ispirate alle GT, Supercar e Hypercar reali. Più scenografica del Touring puro, leggermente meno aggressiva dello Stock — perfetta per chi ama il guidato fluido e le linee delle vere granturismo in scala.",
      specs: {
        scale: "1/10",
        drivetrain: "4WD",
        motor: "Brushless 21.5T (lista EFRA)",
        esc: "Libero, modalità no timing",
        ratio: "Libero",
        battery: "Hardcase 2S, max 8,4V",
        body: "GT, Turismo, Supercar, Hypercar",
        tires: "Ride 26073W",
        weight: "1280 g",
      },
    },
    {
      slug: "touring-stock",
      label: "1/10 Touring Stock",
      short: "Stock 17.5",
      blurb: "17.5T, no timing. La classe più seguita del touring italiano.",
      description:
        "1/10 4WD con motore brushless 17.5T da lista EFRA e regolatore senza timing: la potenza è bloccata, le differenze le fa il pilota. La categoria più diffusa nei campionati indoor italiani — griglie sempre piene e decimi che si giocano sulla cura del setup, sulla gestione gomme e sulla coerenza dal primo all'ultimo giro.",
      specs: {
        scale: "1/10",
        drivetrain: "4WD",
        motor: "Brushless 17.5T (lista EFRA)",
        esc: "Libero, modalità no timing",
        ratio: "Libero",
        battery: "Hardcase 2S, max 8,4V",
        body: "Lista EFRA",
        tires: "Hot Race 32 Carpet",
        weight: "1280 g",
      },
    },
    {
      slug: "touring-modificata",
      label: "1/10 Touring Modificata",
      short: "Modificata",
      blurb: "Open mod, niente limiti. La regina del touring elettrico.",
      description:
        "1/10 4WD elettrico in configurazione \"open\": motore brushless senza vincoli di KV, regolatori a timing libero, telai full-carbon, sospensioni a triangoli regolabili in ogni direzione. Velocità altissime su moquette, ma il dato grezzo non basta — vince chi gestisce energia, monta il setup giusto e non sbaglia per quattordici giri di fila.",
      specs: {
        scale: "1/10",
        drivetrain: "4WD",
        motor: "Libero (open mod)",
        esc: "Libero",
        ratio: "Libero",
        battery: "Hardcase 2S, max 8,4V",
        body: "Lista EFRA",
        tires: "Hot Race 32 Carpet",
        weight: "1280 g",
      },
    },
    {
      slug: "fwd",
      label: "1/10 FWD",
      short: "FWD",
      blurb: "Trazione anteriore. Tutto un altro mondo rispetto al 4WD.",
      description:
        "Touring 1/10 a sola trazione anteriore: comportamento completamente diverso dal 4WD, con sottosterzo da gestire, ingressi tardivi e uscite di curva da costruire col gas. Motore obbligato Hobbywing Justock 21.5T, regolatore Justock con \"no timing\" e rapporto fisso a 5. Costi bassi, sfida tecnica alta — è la categoria che separa chi guida da chi va dietro al manico del 4WD.",
      specs: {
        scale: "1/10",
        drivetrain: "2WD anteriore",
        motor: "Hobbywing Justock 3650 G2/G2.1",
        esc: "Hobbywing Justock XR10 G3/G3S, no timing",
        ratio: "5",
        battery: "Hardcase 2S, max 8,4V",
        body: "Lista ACI",
        tires: "Ride 26073W",
        weight: "1250 g",
      },
    },
    {
      slug: "gt12",
      label: "1/12 GT & LMH",
      short: "GT12",
      blurb: "Pancar 1/12 con motore 13.5T e carrozzerie LMH/GT chiuse.",
      description:
        "Variante più accessibile del 1/12: stesso telaio Pancar ad assale rigido, ma motore brushless 13.5T (più morbido del 6.5T della Open) e carrozzerie chiuse in stile LMH e GT12. Velocità leggermente più contenute, gomme Contact obbligate. Categoria nata negli ultimi anni come porta d'ingresso al mondo 1/12 senza dover affrontare subito le velocità folli della Pancar Open.",
      specs: {
        scale: "1/12",
        drivetrain: "Pancar, assale rigido",
        motor: "Brushless 13.5T (lista EFRA)",
        esc: "Libero, modalità no timing",
        ratio: "Libero",
        battery: "Hardcase 1S, max 4,2V",
        body: "LMH 1/12 e GT12",
        tires: "Contact (JGCF/JT2 ant. · JGCR/JG2CR/JT2/JT3 post.)",
        weight: "790 g",
      },
    },
    {
      slug: "pancar",
      label: "1/12 Pancar Open",
      short: "Pancar",
      blurb: "Pan car 1/12 ad assale rigido. La più pura del 1/12.",
      description:
        "La categoria storica del 1/12 elettrico: telaio piatto ad assale rigido posteriore, niente ammortizzatori (solo flex laterale del telaio), pesi ridottissimi (730 g in ordine di marcia) e batteria 1S a 4,2V. Motore 6.5T EFRA, regolatore senza timing. Velocità altissime su moquette, sensazioni dirette al volante — è il \"feeling puro\" che molti piloti veterani non lasciano per niente al mondo.",
      specs: {
        scale: "1/12",
        drivetrain: "Pancar, assale rigido",
        motor: "Brushless 6.5T (lista EFRA)",
        esc: "Libero, modalità no timing",
        ratio: "Libero",
        battery: "Hardcase 1S, max 4,2V",
        body: "Lista EFRA",
        tires: "Libere · max 20 mm ant. / 40 mm post.",
        weight: "730 g",
      },
    },
    {
      slug: "tt02",
      label: "TT Club (Tamiya TT02)",
      short: "TT Club",
      blurb: "Monomarca Tamiya TT02. La porta d'ingresso al racing indoor.",
      description:
        "Categoria entry-level basata sul Tamiya TT02/TT02R, telaio kit Tamiya semplice, robusto, economico. Motore e regolatore obbligati (combo Hobbywing Justock), rapporto fisso a 5,1, gomme imposte. Costi minimi, ricambi ovunque, regolazioni limitate per evitare la corsa al portafoglio — pensata perché chiunque possa schierarsi e correre senza dover ipotecare casa.",
      specs: {
        scale: "1/10",
        drivetrain: "4WD (Tamiya TT02/TT02R)",
        motor: "Hobbywing Justock 3650 G2/G2.1",
        esc: "Hobbywing Justock XR10 G3/G3S, no timing",
        ratio: "5,1",
        battery: "Hardcase 2S, max 8,4V",
        body: "GT, Turismo, Supercar, Hypercar",
        tires: "Ride 26073W",
        weight: "1400 g",
      },
    },
  ],
  social: {
    facebook: "https://www.facebook.com/p/RcLandia-100063565060634/",
    pullstart: "https://pullstart.tv/track/rc-landia?isUpcoming=0",
    myrcm: "https://www.myrcm.ch/myrcm/main?dId[O]=5244&pLa=it&hId[1]=org",
  },
} as const;

export type NavItem = (typeof site.nav)[number];
export type Category = (typeof site.categories)[number];
